// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpMcUbOxQqcg1pX4CterWqUn2UE6uXkHU',
    appId: '1:31528871369:web:b6846d611cd48dfe7c3418',
    messagingSenderId: '31528871369',
    projectId: 'school-portal-49b1b',
    authDomain: 'school-portal-49b1b.firebaseapp.com',
    storageBucket: 'school-portal-49b1b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2SgLmpnJwc5qjUaFNSnlKpjW2fkSI494',
    appId: '1:31528871369:android:2099c35895389a057c3418',
    messagingSenderId: '31528871369',
    projectId: 'school-portal-49b1b',
    storageBucket: 'school-portal-49b1b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFoDALG4-m0G_2TuQvTbDvhJYMMz2Gf78',
    appId: '1:31528871369:ios:7747c1132553bd567c3418',
    messagingSenderId: '31528871369',
    projectId: 'school-portal-49b1b',
    storageBucket: 'school-portal-49b1b.firebasestorage.app',
    iosBundleId: 'com.example.pbmaPortal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFoDALG4-m0G_2TuQvTbDvhJYMMz2Gf78',
    appId: '1:31528871369:ios:7747c1132553bd567c3418',
    messagingSenderId: '31528871369',
    projectId: 'school-portal-49b1b',
    storageBucket: 'school-portal-49b1b.firebasestorage.app',
    iosBundleId: 'com.example.pbmaPortal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpMcUbOxQqcg1pX4CterWqUn2UE6uXkHU',
    appId: '1:31528871369:web:b811f96603b1ebcb7c3418',
    messagingSenderId: '31528871369',
    projectId: 'school-portal-49b1b',
    authDomain: 'school-portal-49b1b.firebaseapp.com',
    storageBucket: 'school-portal-49b1b.firebasestorage.app',
  );

}